# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-14 17:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('model1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=20)),
                ('rec_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rec1', to='model1.Business')),
                ('rec_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rec2', to='model1.Business')),
                ('rec_3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rec3', to='model1.Business')),
                ('rec_4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rec4', to='model1.Business')),
                ('rec_5', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rec5', to='model1.Business')),
            ],
        ),
    ]
